services:
- docker

jobs:
  include:
    - stage: Build image for version 2.6
      name: linux-sgx-2.6_ubuntu-18.04
      script: docker build 2.6/ubuntu-18.04
    - stage: Build image for version 2.7.1
      name: linux-sgx-2.7.1_ubuntu-18.04
      script: docker build 2.7.1/ubuntu-18.04
