name: ci

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: initc3/linux-sgx

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
          #-
          #  name: Login to Dockerhub
          #  uses: docker/login-action@v1
          #  with:
          #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
          #    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build & push docker image for linux-sgx 2.19 debian 10 (buster)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.19/debian-10/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.19-buster,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.19-buster-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.19 ubuntu 22.04
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.19/ubuntu-22.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.19,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.19-ubuntu22.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.19-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.18 ubuntu 22.04
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.18/ubuntu-22.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.18,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.18-ubuntu22.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.18-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.18 ubuntu 20.04
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.18/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.18-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.18-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.17.1
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.17.1/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.17.1,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.17.1-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.17.1-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.17
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.17/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.17,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.17-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.17-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.16
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.16/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.16,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.16-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.16-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
      -
        name: Build & push docker image for linux-sgx 2.15.1
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.15.1/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.15.1,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.15.1-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.15.1-${{ steps.vars.outputs.short_sha }},
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.15.1
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.15.1,mode=max
      -
        name: Build & push docker image for linux-sgx 2.14
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.14/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.14,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.14-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.14-${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.14
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.14,mode=max
      -
        name: Build & push docker image for linux-sgx 2.13.3 ubuntu 20.04
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.13.3/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.13.3,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.13.3-ubuntu20.04,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.13.3-${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.13.3
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.13.3,mode=max
      -
        name: Build & push docker image for linux-sgx 2.13.3 ubuntu 18.04
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./2.13.3/ubuntu-18.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.13.3-ubuntu18.04
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:2.13.3-ubuntu18.04-${{ steps.vars.outputs.short_sha }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.13.3-ubuntu1804
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache-2.13.3-ubuntu1804,mode=max
