name: ci

on:
  push:
    branches: [ master ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: initc3/linux-sgx

jobs:
  linux-sgx:
    strategy:
      matrix:
        version: [2.13.3, 2.14, 2.15.1, 2.16, 2.17.1, 2.18, 2.19]
        distro: [focal]
        include:
          - version: 2.13.3
            distro: bionic
          - version: 2.18
            distro: jammy
          - version: 2.19
            distro: jammy
          - version: 2.19
            distro: buster
        exclude:
          - version: 2.19
            distro: focal

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build docker image for linux-sgx ${{ matrix.version }} ${{ matrix.distro }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.version }}/${{ matrix.distro }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ matrix.distro }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ matrix.distro }}-${{ steps.vars.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
