name: ci

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  just_build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build docker image for linux-sgx 2.17
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.17/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:2.17,
            initc3/linux-sgx:2.17-ubuntu20.04,
            initc3/linux-sgx:2.17-${{ steps.vars.outputs.short_sha }}
      -
        name: Build docker image for linux-sgx 2.16
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.16/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:2.16,
            initc3/linux-sgx:2.16-ubuntu20.04,
            initc3/linux-sgx:2.16-${{ steps.vars.outputs.short_sha }}
      -
        name: Build docker image for linux-sgx 2.15.1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.15.1/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:2.15.1,
            initc3/linux-sgx:2.15.1-ubuntu20.04,
            initc3/linux-sgx:2.15.1-${{ steps.vars.outputs.short_sha }}
      -
        name: Build docker image for linux-sgx 2.14
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.14/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:2.14,
            initc3/linux-sgx:2.14-ubuntu20.04,
            initc3/linux-sgx:2.14-${{ steps.vars.outputs.short_sha }}
      -
        name: Build docker image for linux-sgx 2.13.3 ubuntu 20.04
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.13.3/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:2.13.3,
            initc3/linux-sgx:2.13.3-ubuntu20.04,
            initc3/linux-sgx:2.13.3-${{ steps.vars.outputs.short_sha }}
      -
        name: Build docker image for linux-sgx 2.13.3 ubuntu 18.04
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.13.3/ubuntu-18.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:2.13.3-ubuntu18.04
            initc3/linux-sgx:2.13.3-ubuntu18.04-${{ steps.vars.outputs.short_sha }}
