name: ci

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  IMAGE_NAME: initc3/gramine

jobs:
  linux-sgx:
    strategy:
      matrix:
        version: [2.13.3, 2.14, 2.15.1, 2.16, 2.17.1, 2.18, 2.19]
        distro: [focal]
        dockerfile: [Dockerfile]
        include:
          - version: 2.13.3
            distro: bionic
            dockerfile: Dockerfile
          - version: 2.18
            distro: jammy
            dockerfile: Dockerfile
          - version: 2.19
            distro: jammy
            dockerfile: Dockerfile
          - version: 2.19
            distro: buster
            dockerfile: Dockerfile
          - version: 2.19
            distro: buster
            dockerfile: aesm.Dockerfile
        exclude:
          - version: 2.19
            distro: focal

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Short SHA
        id: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build docker image for linux-sgx ${{ matrix.version }} ${{ matrix.distro }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.version }}/${{ matrix.distro }}/${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          tags: |
            initc3/linux-sgx:${{ matrix.version }}-${{ matrix.distro }},
            initc3/linux-sgx:${{ matrix.version }}-${{ matrix.distro }}-${{ steps.vars.outputs.short_sha }}
