name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_and_push:
    if: github.event_name	== 'push'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.15.1/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: initc3/linux-sgx:latest, initc3/linux-sgx:2.15.1, initc3/linux-sgx:${{ github.sha }}
          cache-from: type=registry,ref=initc3/linux-sgx:buildcache
          cache-to: type=registry,ref=initc3/linux-sgx:buildcache,mode=max

  just_build:
    if: github.event_name	== 'pull_request'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./2.15.1/ubuntu-20.04/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: linux-sgx:2.15.1, linux-sgx:${{ github.sha }}
